### ISSUE TITLE
neqo-crypto fails to build on macos 

### ISSUE THREAD

**Issue by rmcteggart-r7** [mozilla/neqo#83]
Trying to build neqo and it fails because of neqo-crypto.

I've installed nss and mercurial which fixed some initial errors but still get the below:
```

bindings/nss_sslopt.h:1:10: fatal error: 'ssl.h' file not found, err: true
thread 'main' panicked at 'unable to generate bindings: ()', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```
The first time I built this it actually complained about secerr, not sslopt, but it was the same issue of a header not found.

FYI, std err also tells me to install node-gyp, despite it already being installed globally via npm. Not sure if that's the same issue. I saw that error comes from nss_dev when gyp isn't detected.

```
Please install gyp
Apple clang version 11.0.0 (clang-1100.0.20.17)
Target: x86_64-apple-darwin
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

```

I'm on macos Mojave v10.14.5. Apologies I'm not familiar with nss at all so if this is related to the nss directory hacks that seem to have been added/reverted then let me know.

Thanks!

**Comment by martinthomson** [comment]
> Please install gyp

This is the real problem.  You need to install gyp. This is not node-gyp, which is similar, but not the same.  I haven't tested whether node-gyp works at all.  Getting gyp is a pain, but there might be a brew package for it.  Other wise, go to https://gyp.gsrc.io/ and get the source, which is open-ish but Google have some weird non-open process for accessing it.

You also need ninja (or ninja-build).

Ultimately, this will need to be done by the build automatically, but doing that across different platforms is not our current highest priority.

**Comment by martinthomson** [comment]
A quick follow-up.  Part of the problem here was a failure to capture the NSS build status.  I've fixed that, so the error should be a little clear.

**Comment by rmcteggart-r7** [comment]
@martinthomson I installed gyp (not node-gyp) and still get NSS failures (`NSS build failed`). Unfortunately it just panicks so there's not much to go on. FYI I have ninja installed as well

**Comment by onpaws** [comment]
FYI @rmcteggart-r7 I was able to get it running on macOS, if you still need consider checking out #208

**Comment by rmcteggart-r7** [comment]
Great will take a look thanks @onpaws !
